server:
  port: 5599
  servlet:
    context-path: /
spring:
  zipkin:
    enabled: false
    base-url: http://localhost:5055/
    locator:
      discovery:
        enabled: true
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  sentinel:
    enabled: true
logging:
  level:
    org.example: debug
swagger:
  api:
    title: 'cloud-sys服务'
    version: 'V.1.0.0'
start:
  boot:
    async:
      corePoolSize: 8
      maxPoolSize: 30
      queueCapacity: 10000
      keepAliveSeconds: 300
    auth:
      user:
        token-header: Authorization
      excludePatterns:
        - /test/**
        - /static/**
        - /public/**
        - /security/userPubKey
        - /swagger-ui.html
    xss:
      enable: false
      excludePatterns:
        - /test/**
        - /static/**
        - /public/**