server:
  port: 5599
  servlet:
    context-path: /
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    locator:
      discovery:
        enabled: true
    sender:
      type: web
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
    feign:
      enabled: false
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
  # redis 数据库配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 2
  cloud:
    # sentinel 控制台地址配置
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  # 资源国际化
  messages:
    encoding: UTF-8
    cache-duration: 1000s
    use-code-as-default-message: true
    basename: i18n.test,i18n.error
  resources:
    static-locations: ["/templates/","/resources/","/static/","/public/"]
  mvc:
    static-path-pattern: /static/**
  # thymeleaf
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 开发阶段务必关闭缓存(false)
    cache: false
    servlet:
      content-type: text/html
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
      resolve-lazily: false
  # druid数据源配置
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: root
      filters: stat,wall,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 3
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        # 设置ip白名单
        allow: 127.0.0.1
        # 设置ip黑名单，优先级高于白名单
        deny:
        # 设置控制台管理用户
        login-username: root
        login-password: root
        # 是否可以重置数据
        reset-enable: false
        # 开启druid监控页面
        enabled: true
# 针对特定服指定负载均衡策略
xxxx-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
# ribbon超时间设置，默认是1秒
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
# feign 配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  # openfeign 开启sentinel
  sentinel:
    enabled: true
# 日志输出级别设置
logging:
  level:
    org.example: debug
# swagger 日志标题和版本设置
swagger:
  enable: true
  api:
    title: 'cloud-demo 服务'
    version: 'V1.0.0'
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true
    use-column-label: true
    jdbc-type-for-null: null
# seata 分布式事务配置
seata:
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: seata
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: seata
      cluster: default
# 自定义配置
start:
  uploadFolder: /home/data/uploads
# 异步线程池配置
async:
  corePoolSize: 8
  maxPoolSize: 30
  queueCapacity: 10000
  keepAliveSeconds: 300
auth:
  service-name: cloud-sys
  user:
    # token 请求头 key 设置
    token-header: Authorization
  # 认证拦截器要排除的 url配置
  excludePatterns:
    - /test/**
    - /static/**
    - /public/**
    - /userPubKey
    - /swagger-ui.html
xss:
  # 是否开启 xss 过滤
  enable: false
  # xss 过滤要排除的 url
  excludePatterns:
    - /test/**
    - /static/**
    - /public/**